Fix/oc (#41)
* build/root/usr/local/bin/run: download latest 'oc' client if missing from PATH

Prevent failures due to missing `oc` command (in pre-release):

```
/usr/local/bin/run: line 31: oc: command not found
error: failed to execute wrapped command: exit status 127
```

* roles/nv_gpu/tasks/install.yml: wait 5min for CRDs

The CI is still failing when waiting only 1min40s:n

```
 fatal: [localhost]: FAILED! => {
    "attempts": 10,
    "changed": true,
    "cmd": [
        "oc",
        "apply",
        "-f",
        "roles/nv_gpu/files/041_customresources.yaml"
    ],
    "delta": "0:00:00.997076",
    "end": "2021-01-22 23:54:02.116023",
    "invocation": {
        "module_args": {
            "_raw_params": "oc apply -f \"roles/nv_gpu/files/041_customresources.yaml\"",
            "_uses_shell": false,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 1,
    "start": "2021-01-22 23:54:01.118947",
    "stderr": "error: unable to recognize \"roles/nv_gpu/files/041_customresources.yaml\": no matches for kind \"NodeFeatureDiscovery\" in version \"nfd.openshift.io/v1alpha1\"",
    "stderr_lines": [
        "error: unable to recognize \"roles/nv_gpu/files/041_customresources.yaml\": no matches for kind \"NodeFeatureDiscovery\" in version \"nfd.openshift.io/v1alpha1\""
    ],
    "stdout": "",
    "stdout_lines": []
}
```

* roles/nv_gpu/tasks/install.yml: remove trailing spaces

* build/root/usr/local/bin/run: do not print git commit notes in the CI run info

* roles/nv_gpu/tasks/ci_checks.yml: capture more info when tests succeed