build/Dockerfile: use wget instead of curl to download ocm
to avoid this kind of error:
```
STEP 11/33: RUN curl --silent -L ${OCM_CLI_URL} --output /usr/local/bin/ocm
STEP 12/33: RUN file /tmp/ocm | grep ELF -q # ensure that the file is an ELF binary
error: build error: error building at STEP "RUN file /tmp/ocm | grep ELF -q # ensure that the file is an ELF binary": error while running
runtime: exit status 1
```